//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleEFProjectUnderTest
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Helpers;
    
    public partial class sampledataEntities : DbContext
    {
        public sampledataEntities()
            : base(EFContextHelper.ConnectionString("FRANK-PC\\FRANK", "sampledata", "Model1", "", ""))
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Product> Products { get; set; }
        public DbSet<ProductType> ProductTypes { get; set; }
        public DbSet<Store> Stores { get; set; }
    }
}
