//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleEFProjectUnderTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductId { get; set; }
        public int ProductType { get; set; }
        public string Name { get; set; }
        public int store { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual ProductType ProductType1 { get; set; }
    }
}
